### ISSUE TITLE
Wahoo should load common configurations by default (See #6)

### ISSUE THREAD

**Issue by bucaran** [fish-shell/wahoo#10]
For example, `.dir_colors`.

See #6

**Comment by gretel** [comment]
supporting this, if we could agree on the meaning of 'common' first :books:

**Comment by bucaran** [comment]
Yes. What are some of these very common configurations we could rely on Wahoo to do for us?

I prefer leaving that up to the user in her `~/.dotfiles/init.fish` file, but if I am open to suggestions.

**Comment by gretel** [comment]
i suggest leaving users with `~/.dotfiles/init.fish` and have a wiki page with nice examples and stuff

**Comment by bucaran** [comment]
:+1:
