### ISSUE TITLE
Ideas for Packages

### ISSUE THREAD

**Issue by bucaran** [fish-shell/wahoo#18]
+ What do you want to see?

+ What do you think would make a good fish package?

**Comment by hauleth** [comment]
* `z` or equivalent written in fish
* `hub` - aliases `git` to `hub` + eventually installation
* `copy`/`paste` scripts that are multiplatform (OSX, Linux & BSD)
* `ssh-agent`
* `serve` - static-files HTTP server (`nc` + fish, Python or Ruby, choose must be made)
* `brew` completion & setup
* some people probably will be happy if there will be `rvm` package
* some kind of easter eggs (like `sl`)
* `gist` - publish snippets on https://gist.github.com/
* `tmux` integration

That's for now.

**Comment by bucaran** [comment]
:+1: 
Thanks. I will go ticking those checkboxes as I can.

**Comment by bucaran** [comment]
Does `serve` actually make sense? You can use `python -m http.server` or `npm install serve; serve`, and there are many more. 

What would the `serve` package do exactly?

**Comment by TeddyDD** [comment]
Idk, maybe completion generator that would use help of given program instead of manpage? but that could be quiet hard to write

**Comment by gretel** [comment]
copying from my previous omf config - the plugins i really 'need':
```
"direnv"
"emoji-clock"
"jump"
"keychain"
"osx_manpath"
"peco"
"screen"
"sublime"
```

**Comment by bucaran** [comment]
@gretel Sounds good. I will work on this tomorrow.

**Comment by s0r00t** [comment]
For me, I'd just like 'bobthefish' theme and the 'node' plugin from OMF.
Maybe they don't need any port and cloning them straight will work.

**Comment by bucaran** [comment]
@s0r00t What about a `serve` plugin that cascades to whatever you have in your system? I use `serve` via `npm i -g serve`, but the plugin could check whether you have `serve`, and if not try `python -m http.server` and if that also fails then use PHP or Ruby.

I haven't tried cloning bobthefish, because it's quite a long plugin (and a bit slow and I have been meaning to make my own leaner version), but it might just work out of the box. You can give it a shot, and if it works, fork it from OMF, and make a Wahoo version.

In the mean time I use [Hogan](https://github.com/bucaran/hogan) which is not terribly inferior.

Thanks for trying Wahoo and let me know if you have any further comments.

**Comment by s0r00t** [comment]
@bucaran I personally use http-server (npm pkg) + ngrok for most of my tests :P Such a plugin would be useless in my opinion. A simple 'function serve; <favourite command>;' end is enough.

I'll fork bobthefish and see what happens.

**Comment by bucaran** [comment]
:+1: Great

**Comment by s0r00t** [comment]
bobthefish works OOTB, just clone it in /themes and wa use theme-bobthefish.

**Comment by bucaran** [comment]
Nice. Will think about a strategy to do this officially. I would prefer if the author could still offer support for the theme as well.

Thanks for figuring this out @s0r00t

**Comment by s0r00t** [comment]
A rewrite could be possible, considering your work on Hogan. Might look onto contributing :+1:

**Comment by gretel** [comment]
i suggest we should at least add completions for the following:
* `homebrew`
* `git-flow`
* `rubygems`
* `pip`
* `npm`

in terms of plugins i recently came up with:
* `goenv` https://github.com/pwoolcoc/goenv
* `mackup` https://github.com/lra/mackup

**Comment by bucaran** [comment]
:+1: Should these completions be added by default with Wahoo or as a plugin?

**Comment by hauleth** [comment]
IMHO as a plugin

--
Łukasz Jan Niemier

Dnia 24 lip 2015 o godz. 03:55 Jorge Bucaran <notifications@github.com> napisał(a):

**Comment by bucaran** [comment]
@hauleth I think so too. 

> #### That and whatever shell initialization required by that package is what plugins for these tools _should_ be.

**Comment by gretel** [comment]
:+1:
