### ISSUE TITLE
Wahoo vs oh-my-fish?

### ISSUE THREAD

**Issue by Globegitter** [fish-shell/wahoo#43]
Hey there, I am an oh-my-fish user and just found this project. It does seem to have some overlap, with plugins and themes so I was wondering what exactly the differences are. Are they complimentary to use, or would you choose one over the other?

**Comment by bucaran** [comment]
Good question. Unfortunately they are not complimentary. Wahoo should be the new OMF. 

+ Wahoo was carefully designed __from day one__ to use fishshell powerful features such as autoloading, completions and events consistently.

+ Wahoo has a cleaner and higher level plugin system based in events.

+ Wahoo is thoroughly documented. Everything you need to know is in the README.

+ Wahoo is a decentralized package system. We simply maintain a registry with URLs to packages. You don't even need to be in the registry `wa get <URL>` will attempt to install a package from that URL you provide.

> When Wahoo was released, OMF was still a centralized system with plugins and themes living in the same repository. Eventually they caught up, but each package still requires a repository in the organization. This means one has to create a team for each package inside the organization. 

+ It learns from OMF mistakes.

> Oh My Fish! was a great project and I learned a lot from it and I am still a maintainer and [top committer](https://github.com/oh-my-fish/oh-my-fish/graphs/contributors?from=2012-07-22&to=2015-07-17&type=a). I help rebuilt many of the core fundamentals of OMF, added many plugins, improved the documentation and wrote the test framework, but after a while I decided I was ready to move on and wanted to apply all this knowledge to create a new, simpler yet more powerful framework.

**Comment by Globegitter** [comment]
@bucaran That is good to hear and now that wahoo moved to the official fish-shell repo even better :) Will give it a try. Would also be great to see forces of oh-my-fish and wahoo combined (probably within wahoo) but I suppose that is quite a different matter.

**Comment by bucaran** [comment]
@Globegitter [I tried](https://github.com/oh-my-fish/oh-my-fish/issues/498), but was met with contempt. Perhaps I was too pushy? I am not a good polititian it seems :disappointed:

**Comment by TeddyDD** [comment]
I'd like to add all oh-my-fish themes I tried works well with Wahoo :+1:

**Comment by bucaran** [comment]
I have added a FAQ to address some of these questions. Feel free to reopen or create a new issue if you have more questions :smile:

**Comment by rubenvarela** [comment]
I hadn't heard of Wahoo.

I found this read, https://github.com/wa/wahoo/issues/43, interesting. Thank you for the link! :)
