### ISSUE TITLE
Wahoo should append its own config to config.fish and not back it up

### ISSUE THREAD

**Issue by s0r00t** [fish-shell/wahoo#53]
This would avoid the step of migrating custom config used before installing Wahoo.

Append its configuration directives at the end of an existing config.fish would avoid creating a config.fish.bak, and (for example) breaking existing functions and such.

**Comment by bucaran** [comment]
This is not a trivial task. Just appending is easy enough, but the user may have more complicated configurations in place. How do we deal with those cases?

**Comment by s0r00t** [comment]
Yes.

**Comment by gretel** [comment]
i don't feel the added complexity is worth the risk of still messing up user's config. if something'd be changed it'd vote for something interactive, like asking the user.

**Comment by bucaran** [comment]
Not ill-intended, but IMO only naive users would expect Wahoo to merge your existing configuration :smile: 

I vote to close down this feature request.

**Comment by gretel** [comment]
:+1:

**Comment by bucaran** [comment]
@s0r00t Close? :smile:

**Comment by s0r00t** [comment]
Well, I myself lost configuration files because of multiple Wahoo reinstall (testing reasons), and overriding the config files.
It overwrites config.fish.bak even if it already exists.
I think there is still an issue.

**Comment by bucaran** [comment]
It will override any `config.fish.bak`. Do you want to make a backup of the copy?

**Comment by gretel** [comment]
* assume existing `config.fish`
* install `wahoo` → `config.fish` gets moved to `config.fish.bak`
* install `wahoo` again →  `config.fish` gets moved to `config.fish.bak` _overwriting_ the previous backup

solutions:
* use `rsync` to stagger naming of backup copies (another dependency)
* regexp over existing `config.fish` and only add stuff if it seems to be missing (will introduce side-effects)
* use a timestamp for naming by `date` or so

**Comment by bucaran** [comment]
Use a timestamp is a simple solution, but I wonder if this is really worth it.
