### ISSUE TITLE
'wa update' does not 'git set-url upstream' to the updated repo urls

### ISSUE THREAD

**Issue by gretel** [fish-shell/wahoo#54]
which leaves me with `upstream` set to
```
upstream	git@github.com:bucaran/wahoo.git (fetch)
upstream	git@github.com:bucaran/wahoo.git (push)
```

**Comment by bucaran** [comment]
Here is the code for wa-update, what is the problem:

```fish
function wa_update
  set -l repo "upstream"
  test -z (git config --get remote.upstream.url)
    and set -l repo "origin"

  if git diff-index --quiet HEAD -- >/dev/null ^&1
    git pull $repo master >/dev/null ^&1
  else
    git stash >/dev/null ^&1
    if git pull --rebase $repo master >/dev/null ^&1
      git stash apply >/dev/null ^&1
    else
      wa_util_sync "origin"
    end
  end
end
```

**Comment by s0r00t** [comment]
Maybe add a small check to the remote to see if it's still correct.
@gretel's remote is still under the old repo address, and I think it's the problem that he reported.

**Comment by gretel** [comment]
> @gretel's remote is still under the old repo address, and I think it's the problem that he reported.
i don't follow. my remotes are not related to this issue at all. this issue is about 'wahoo', not my repos.

**Comment by s0r00t** [comment]
Yes. wa update does not check the local upstream remote, to see if it's correct.

**Comment by gretel** [comment]
but why should wahoo mess with my repos?

**Comment by s0r00t** [comment]
I am not talking about your repos. I am talking about the remotes your local Wahoo install uses as upstream.
As you showed it, the old upstream remote is still used.
Therefore, wa update needs to check if it's using the new remote; if not, change it.

**Comment by bucaran** [comment]
@gretel I want to help you fix this problem, but I still can't follow. If you can explain this in a way I can understand I will fix this right away :smile:

**Comment by s0r00t** [comment]
@bucaran I've been working on this, to update upstream remote ;)

**Comment by bucaran** [comment]
AFIC `wa update` should update against the upstream, which is the official repo, not against `origin` which should be the user's fork.

**Comment by s0r00t** [comment]
So :
-Check if origin is the official repo
   -If so, update from there
-If not, check if upstream is set
   -If so, check if it's the official repo
      -Change it if needed and update from there

**Comment by bucaran** [comment]
@s0r00t Thanks! I see.

**Comment by s0r00t** [comment]
I'd like to work on it, for a first PR.

**Comment by bucaran** [comment]
@s0r00t Go for it.

**Comment by s0r00t** [comment]
The fix is going well, but Wahoo says it failed to update when there's no update to do.
Is that default behavior? I can't test it and I have no memory.

**Comment by gretel** [comment]
@bucaran no, because it's not just a fix but a change that will bring different issues up. we should agree on something first and then try to implement code that actually is about that. regards

**Comment by bucaran** [comment]
Closing this in favor of #54.
