### ISSUE TITLE
"wrong" references to packages 'osx_manpath' and 'peco'

### ISSUE THREAD

**Issue by gretel** [fish-shell/wahoo#55]
these are the two repos which i can't access the settings, i.e. don't have admin rights.
so i can't change their names. _but_ the references in `db` have been changed already, so:
```
Installing osx_manpath...
Username for 'https://github.com':
Password for 'https://github.com':
Could not install package.
Installing peco...
Username for 'https://github.com':
Password for 'https://github.com':
Could not install package.
```
please check on my permissions of the two repos. regards

**Comment by bucaran** [comment]
Done

**Comment by gretel** [comment]
thx
