### ISSUE TITLE
descriptions for packages

### ISSUE THREAD

**Issue by liljaylj** [fish-shell/wahoo#57]
it will be nice to know what package is about before/after install. i mean something like `pip search <query-string>`.
for example:
```
> wa search ansimble
ansimble             - Ansible development package for Wahoo
```

**Comment by bucaran** [comment]
Sounds fair. This would require modifying the database to add the descriptions, which will of course have side effects :stuck_out_tongue_winking_eye: 

Let me see what I can come up with in the next following days.

**Comment by s0r00t** [comment]
Isn't this a duplicate of #26 ?

**Comment by bucaran** [comment]
Yes, it seems so.
