### ISSUE TITLE
travis does not actually test changes

### ISSUE THREAD

**Issue by gretel** [fish-shell/wahoo#65]
because `curl -L git.io/wa | sh` will not fetch branches like we use in PRs,  solely `master`.
possible solution is to run `bootstrap.sh` within travis instead.

**Comment by gretel** [comment]
while i don't address building `fish` because i feel it's unrelated from testing other stuff it basically works fine using `bootstrap.sh`.

**Comment by bucaran** [comment]
I don't understand this issue. What branches?

**Comment by gretel** [comment]
would you mind comparing the output of travis with what shows up in the according commits?

**Comment by bucaran** [comment]
What commits? Please clarify or close.

**Comment by gretel** [comment]
the purpose of continous integration is to actually integrate the changes in testing. it's obvious that it does not happen, and that was the reason why i set up a travis job for my fork, because i feel it's a very time-consuming task to discuss this issue.
in addition, i dislike being pushed into either giving you an explanation or close this. i would kinda expect you to at least try to understand what this issue is about.
closing in favor for my 'forked' travis job.

**Comment by bucaran** [comment]
Are you saying maybe _CI does not test actually test framework, just install Wahoo and prints a hello message?

**Comment by gretel** [comment]
it simply is about `curl -L git.io/wa` not returning the code which the travis run should check.

**Comment by gretel** [comment]
now that https://github.com/fish-shell/wahoo/pull/62 is merged it is possible to compare the git revisions of what got commited and what is actually 'tested' when travis calls `curl -L git.io/wa`:

```
[14:20:38] Wahoo revision id → 3e3948a319f6c446bbd3f4a67250b4ba52aa2cb6
```
