### ISSUE TITLE
all links to wahoo-foundry are 404'ing

### ISSUE THREAD

**Issue by mmlb** [fish-shell/wahoo#66]

**Comment by bucaran** [comment]
Hi @mmlb! Please update Wahoo, the registry was updated recently and you probably have a version with the old incorrect links. 

<rant>
If `git` followed link redirections (I presume it does not) you would not be getting any errors though, as GitHub supports dead link correction as you can see from this:

https://github.com/wahoo-foundry/pkg-battery
</rant>

**Comment by mmlb** [comment]
I'm talking about the wiki (https://github.com/fish-shell/wahoo/wiki/Packages-and-Themes). Mostly looking around to browse packages and am not sure where I can find them. :/

**Comment by bucaran** [comment]
My bad. Fixed.

**Comment by mmlb** [comment]
np :+1:
